report_config:
  format: csv # csv, md or html
  s3_config:
    access_key: testy
    secret_key: testy
    region: us-east-1
    endpoint: http://10.3.8.31:80
    bucket: test
    skipSSLverify: true

global_config:
  ultra_large_scale: false
  server_side_listing: false

  feishu_url: "feishu_url"
  fs_types:
    - xfs
    - gpfs
  tasks_file: deploy/data_sources.test.txt

  file_list_dir: /mnt/yrfs/public-data/user/zhengliang/
  file_list_dir_fs_type: xfs
  concurrency: 3
